# Порт сервера
server:
  port: 8081

# Конфигурация Camunda
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
      lastName: User
    client:
      base-url: http://localhost:8081/engine-rest
      async-response-timeout: 20000

# Конфигурация базы данных
spring:
  datasource:
    url: jdbc:h2:mem:camunda
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

# Логирование
logging:
  level:
    org.camunda.bpm: INFO
    com.example: DEBUG 